version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gamenight-postgres
    environment:
      POSTGRES_USER: gamenight
      POSTGRES_PASSWORD: gamenight
      POSTGRES_DB: gamenight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gamenight"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
